In [3]:
import numpy as np

In [1]:
print("Array Operations")

Array Operations


In [2]:
print("Arithematic operations")

Arithematic operations


In [4]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [7]:
sum = a1+a2
sum

array([ 7,  9, 11, 13, 15])

In [8]:
sub = a1-a2
sub

array([-5, -5, -5, -5, -5])

In [9]:
mul = a1*a2
mul

array([ 6, 14, 24, 36, 50])

In [10]:
div = a1/a2
div

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [11]:
mod = a1%a2
mod

array([1, 2, 3, 4, 5])

In [12]:
fd = a1//a2
fd

array([0, 0, 0, 0, 0])

In [13]:
exp = a1**a2
exp

array([      1,     128,    6561,  262144, 9765625])

In [14]:
print('Broadcasting')

Broadcasting


In [15]:
l = [10,20,30,40,50]
arr = np.array(l)

In [16]:
arr + 10

array([20, 30, 40, 50, 60])

In [17]:
print("Deep shallow copy")

Deep shallow copy


In [31]:
arrr = np.arange(1,21)
arrr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [36]:
slice = arrr[:5]
slice = slice * 10
slice 

array([10, 20, 30, 40, 50])

In [37]:
arrr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [38]:
print("Matrix Operation")

Matrix Operation


In [41]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [43]:
A * B

array([[ 5, 12],
       [21, 32]])

In [44]:
A @ B 

array([[19, 22],
       [43, 50]])

In [53]:
A.T

array([[1, 3],
       [2, 4]])

In [54]:
B.T

array([[5, 7],
       [6, 8]])

In [55]:
print("Advance array Manipulation")

Advance array Manipulation


In [56]:
print("Stacking array")

Stacking array


In [59]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [60]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [61]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [63]:
print("Spliting array")

Spliting array


In [64]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [66]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]