In [2]:
import numpy as np

In [13]:
print("Basic Array Creation")

Basic Array Creation


In [6]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [8]:
a = [1,2,3.5,'hello']
a

[1, 2, 3.5, 'hello']

In [9]:
np.array(a)

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [10]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
print("Array Genration function")

Array Genration function


In [16]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [17]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
arr = np.ones((4,9))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [22]:
print("Random Generation function")

Random Generation function


In [3]:
arr = np.random.rand(5)
arr

array([0.83289332, 0.66772527, 0.73857969, 0.21455353, 0.47819322])

In [9]:
arr = np.random.randn(10)
arr

array([ 1.07797018e+00, -1.67793812e-01,  3.26507717e-01,  5.92577183e-01,
       -3.54511092e-01,  1.92029004e-01, -9.78308401e-01, -6.67753985e-01,
       -4.19224462e-01, -9.11579672e-04])

In [15]:
arr = np.random.randint(10,20,10)
arr

array([13, 14, 11, 13, 14, 13, 10, 12, 18, 18], dtype=int32)

In [16]:
print("Array Attributes")

Array Attributes


In [17]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr.shape

(3, 3)

In [19]:
arr.size

9

In [20]:
arr.dtype

dtype('int64')

In [21]:
print("Array Methods")

Array Methods


In [22]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr.min()

np.int64(1)

In [24]:
arr.max()

np.int64(9)

In [25]:
arr.sum()

np.int64(45)

In [26]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [27]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [29]:
arr.mean()

np.float64(5.0)

In [30]:
arr.std()

np.float64(2.581988897471611)

In [31]:
arr.argmax()

np.int64(8)

In [32]:
arr.argmin()

np.int64(0)

In [33]:
print("Reshaping and Resizing")

Reshaping and Resizing


In [35]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [36]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [38]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])