In [2]:
import numpy as np

In [3]:
print("NUMPY indexing and slicing of vectors")

NUMPY indexing and slicing of vectors


In [5]:
arr = np.arange(31,41)
arr

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [6]:
arr[6]

np.int64(37)

In [7]:
arr[1:4]

array([32, 33, 34])

In [8]:
arr[:]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [10]:
arr[3:]

array([34, 35, 36, 37, 38, 39, 40])

In [11]:
arr[3::2]

array([34, 36, 38, 40])

In [12]:
print("NUMPY indexing and slicing of matrix")

NUMPY indexing and slicing of matrix


In [13]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [14]:
arr[0]

array([1, 2, 3, 4, 5])

In [18]:
arr[2,4]

np.int64(15)

In [24]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [25]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [26]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [27]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [28]:
print("Boolean indexing")

Boolean indexing


In [32]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [30]:
bool_index = arr%2 == 0 
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [33]:
new_arr = arr[bool_index]
new_arr

array([12, 14, 16, 18, 20])